'use client';
import {useState,useEffect} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {scan} from './scanner';
import type {Stock} from './scanner';
import {PatternChart} from './pattern-chart';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {PatternPanel} from './pattern-panel';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
export default function Home(){const [stocks,setStocks]=useState<Stock[]>([]);const [session,setSession]=useState('');const [dataStatus,setDataStatus]=useState('Loading saved scan…');useEffect(()=>{fetch('/version1-data.json',{cache:'no-store'}).then(async r=>{if(r.status===404){setDataStatus('Run the scanner to generate results.');return;}if(!r.ok)throw Error();const data=await r.json() as {stocks:Stock[];session:string};setStocks(data.stocks);setSession(data.session);setDataStatus(data.stocks.length?'':'Run the scanner to generate results.');}).catch(()=>setDataStatus('Could not load saved results. Run the scanner again and reload.'));},[]);const [filter,setFilter]=useState('All signals');const [ran,setRan]=useState(false);useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'run_snapshot_scan',description:'Scan the saved liquidity-selected stock snapshot for confirmed consolidation breaks. No live refresh.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');setRan(true);return {snapshotDate:session,signals:scan(stocks).map(r=>({symbol:r.symbol,direction:r.direction,relativeVolume:r.ratio}))};}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[stocks,session]);const all=scan(stocks);const rows=all.filter(r=>filter==='All signals'||r.direction===filter);return <main>
<header><div className="brand"><span className="logo">↗</span> CLOSE<span className="brand-sub"> / STOCK SCANNER</span></div><span className="session">US EQUITIES · DAILY CLOSE</span></header>
<Tabs defaultValue="v1" style={{marginTop:24}}><TabsList aria-label="Scanner version" style={{height:48}}><TabsTrigger value="v1" style={{padding:"12px 20px"}}>Version 1 · Ranges</TabsTrigger><TabsTrigger value="v2" style={{padding:"12px 20px"}}>Version 2 · Patterns</TabsTrigger></TabsList><TabsContent value="v1">{stocks.length===0?<section className="results" style={{padding:24,marginTop:24}}><h2>{dataStatus}</h2><p>Configure your Alpaca keys in .env.local, then run <code>pnpm scan</code> and reload this page.</p></section>:<><section className="title"><div><p className="eyebrow">CONFIRMATION FIRST</p><h1>Beyond the range.</h1><p className="muted">Breakouts and breakdowns that passed the closing bell.</p></div><button className="run" onClick={()=>setRan(true)}>↻ Rescan saved data</button></section>
<div className="notice"><span className="demo-tag">DATED SNAPSHOT</span><span>Same liquidity-selected 500 stocks as Version 2 · {session} close · Alpaca SIP daily data. Saved snapshot, not a live feed.</span></div>
<section className="rules"><div><span>01 / UNIVERSE</span><strong>Market cap &gt; $5B</strong><p>Top 500 by average dollar volume · USD</p></div><div><span>02 / PRICE CONFIRMATION</span><strong>Close beyond consolidation</strong><p>Detected sideways base · 8–15 sessions</p></div><div><span>03 / VOLUME CONFIRMATION</span><strong>Volume &gt; 20-day average</strong><p>Signal day excluded from the average</p></div></section>
<section className="stats"><div><span>Confirmed signals</span><strong>{all.length.toString().padStart(2,'0')}</strong></div><div><span><i className="dot up"/> Breakouts</span><strong className="positive">{all.filter(r=>r.direction==='Breakout').length.toString().padStart(2,'0')} <small>↗</small></strong></div><div><span><i className="dot down"/> Breakdowns</span><strong className="negative">{all.filter(r=>r.direction==='Breakdown').length.toString().padStart(2,'0')} <small>↘</small></strong></div><div><span>Stocks evaluated</span><strong>{stocks.length} <small className="muted">of {stocks.length} · no missing data</small></strong></div></section>
<section className="results"><div className="results-head"><div><h2>Confirmed signals <span className="count">{rows.length}</span></h2><p className="muted">Session · {session} · Ranked by relative volume</p></div><div className="filters" aria-label="Signal filter">{['All signals','Breakout','Breakdown'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
<Table><TableHeader><TableRow>{['Company','Signal','Market cap','Close','Broken level','Beyond level','Day volume','20D avg','Rel. volume'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.symbol}><TableCell><strong>{r.symbol}</strong><span className="company">{r.name}</span></TableCell><TableCell><span className={'signal '+(r.direction==='Breakout'?'positive':'negative')}>{r.direction==='Breakout'?'↗':'↘'} {r.direction}</span></TableCell><TableCell>${r.cap/1e9}B</TableCell><TableCell>{money(r.day.close)}</TableCell><TableCell>{money(r.level)}</TableCell><TableCell className={r.distance>0?'positive':'negative'}>{r.distance>0?'+':''}{r.distance.toFixed(2)}%</TableCell><TableCell>{(r.day.volume/1e6).toFixed(2)}M</TableCell><TableCell>{(r.avg/1e6).toFixed(2)}M</TableCell><TableCell><strong>{r.ratio.toFixed(2)}×</strong><div className="volume-bar"><i style={{width:Math.min(100,r.ratio/3*100)+'%'}}/></div></TableCell></TableRow>)}{rows.length===0&&<TableRow><TableCell colSpan={9}>No confirmed signals match this filter.</TableCell></TableRow>}</TableBody></Table><div className="table-foot"><span>✓ Completed daily candles only</span><span aria-live="polite">{ran?`Snapshot scan complete · ${stocks.length} stocks evaluated`:`${stocks.length} / ${stocks.length} covered · ${stocks.length-all.length} did not qualify`}</span></div></section>
<p className="muted" style={{marginTop:16}}>Coverage: all {stocks.length} loaded symbols have daily data through {session}. Universe and market caps: <a href="/liquidity-universe.csv">Shared liquidity universe</a> / <a href="https://www.nasdaq.com/market-activity/stocks/screener">Nasdaq</a>. Prices and volumes: Alpaca SIP, split-adjusted. <a href="/version1-signals.csv" download>Download signals CSV ↗</a></p><section style={{marginTop:28}}><h2>Pattern evidence</h2><p className="muted">Automated sideways-consolidation heuristic. The signal candle is excluded when finding the base.</p>{rows.map(r=><article key={r.symbol} className="results" style={{marginTop:20}}><div className="results-head"><div><h2>{r.symbol} · Consolidation {r.direction?.toLowerCase()}</h2><p className="muted">{r.baseStart} – {r.baseEnd} · {r.sessions} sessions · Close {money(r.day.close)}</p></div><span className={r.direction==='Breakdown'?'negative':'positive'}>{r.ratio.toFixed(3)}× volume {r.ratio<1.1?'· Marginal volume confirmation':''}{Math.abs(r.distance)<.1?' · Marginal price break':''}</span></div><div style={{overflowX:'auto'}}><PatternChart r={r}/></div><div className="table-foot"><span>Above resistance: {money(r.high)} · Below support: {money(r.low)}</span><a href='https://docs.alpaca.markets/us/reference/stockbars' target="_blank" rel="noreferrer">Alpaca SIP data source ↗</a></div></article>)}</section>
<section className="method"><div><h2>How the pattern is detected</h2><p>Search the 8–15 sessions immediately before the signal candle, longest first. A base must be no wider than 18% of its midpoint, with fitted closing-price drift no greater than 35% of its height. Require two upper-zone touches and two lower-zone touches, each pair separated by at least three sessions. Upper and lower touch zones cover 20% and 25% of the base height.</p></div><div><h3>Confirmation comes after the close.</h3><p>The completed close must exceed the detected base high or fall below its low, with volume strictly above the preceding 20-session average and market cap above $5B. These are heuristic consolidation signals; Version 2 scans flags, wedges and head-and-shoulders with price rules in the Version 2 tab; those results are experimental. A confirmed break can still fail.</p></div></section><footer>CLOSE / SCANNER V3<span>Saved {session} data · Rescan recalculates; it does not fetch new prices.</span></footer>
</>}</TabsContent><TabsContent value="v2"><PatternPanel/></TabsContent></Tabs></main>}
