'use client';
import {useEffect,useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {rankStrength} from './strength';
import type {PatternReport} from './patterns';
const strengthColor=(label:string)=>label==='Strong'?'#46d7a6':label==='Moderate'?'#ffd56a':label==='Weak'?'#ff8895':'#b6c2cf';
export function PatternPanel(){
 const [strengthFilter,setStrengthFilter]=useState('All strengths');
 const [report,setReport]=useState<PatternReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[showRejected,setShowRejected]=useState(false);
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/pattern-results.json',{cache:'no-store'});if(!r.ok)throw Error();setReport(await r.json());}catch{setError('Could not load the saved pattern report. Try again.');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 const confirmed=(report?.results.filter(r=>r.status==='Confirmed')??[]).sort(rankStrength);
 const visible=(showRejected?[...(report?.results??[])].sort(rankStrength):confirmed).filter(r=>strengthFilter==='All strengths'||r.strength?.label===strengthFilter);
 return <section className="results" style={{marginTop:28}}><div className="results-head"><div><p className="eyebrow">VERSION 2 · EXPERIMENTAL</p><h2>Price-based patterns <span className="count">{confirmed.length}</span></h2><p className="muted">Flags · Wedges · Head and shoulders</p></div><button className="run" onClick={refresh} disabled={loading}>{loading?'Loading…':'Reload saved report'}</button></div>
 <div style={{padding:24}} aria-live="polite">{error&&<p role="alert">{error}</p>}{!report&&!error&&<p>Loading pattern report…</p>}{report&&<><p><strong>{report.status}</strong>{report.universeLabel?" · "+report.universeLabel:""} · {report.reviewed} / {report.requested} stocks evaluated{report.session?' · Session '+report.session:''}{report.model?' · '+report.model:''}</p>
 {report.liquidity&&<div className="notice" style={{margin:'16px 0',display:'block'}}><strong>Selected by trading activity, not index membership</strong><p>Market cap &gt; $5B · Average of daily close × volume across 20 completed sessions, excluding the signal day.</p><p>{report.liquidity.rankingStart} – {report.liquidity.rankingEnd} · {report.liquidity.rankable} ranked equities · Selection cutoff ${(report.liquidity.cutoff/1e6).toFixed(1)}M/day</p><p>Membership refreshes on the first scan each week. ADRs included; funds, preferred shares, warrants and units excluded. {report.liquidity.exclusions>0?`${report.liquidity.exclusions} listings lacked supported assets or complete liquidity data; see the universe report.`:''}</p><a href="/liquidity-universe.csv" download>Download all 500 stocks with liquidity ranks ↗</a> · <a href="/liquidity-universe.json" download>Universe details and exclusions</a></div>}
 <p className="muted">Price rules discover and validate patterns. AI review: not run; no OpenAI calls are required. These experimental results have not yet been validated against a manually labeled benchmark.</p>
 {report.reviewed===0&&<p>No completed price scan is available yet. Run the local price-based scanner. Reloading this report does not call the AI or refresh prices.</p>}
 <section style={{margin:'24px 0'}}><h3>Breakout strength · strongest first</h3><p className="muted">Strength grades the confirmed move, not the probability of a profitable trade or the accuracy of the pattern label. Multiple pattern labels may describe the same stock move.</p><div style={{display:'flex',gap:24,flexWrap:'wrap',margin:'16px 0'}}>{['Strong','Moderate','Weak'].map(label=><div key={label}><strong style={{color:strengthColor(label),fontSize:24}}>{confirmed.filter(r=>r.strength?.label===label).length}</strong> {label} patterns</div>)}</div>
 <Select value={strengthFilter} onValueChange={value=>setStrengthFilter(value??'All strengths')}><SelectTrigger aria-label="Filter breakout strength" style={{minWidth:180,height:42}}><SelectValue/></SelectTrigger><SelectContent>{['All strengths','Strong','Moderate','Weak'].map(label=><SelectItem key={label} value={label}>{label}</SelectItem>)}</SelectContent></Select>
 {confirmed.length>0&&<Table><TableHeader><TableRow>{['Stock / pattern','Signal','Strength','Evidence score','Volume','Break distance'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.filter(r=>r.status==='Confirmed').map(r=><TableRow key={r.symbol+r.pattern}><TableCell><a href={'#pattern-'+r.symbol+'-'+r.pattern.replaceAll(' ','-')}>{r.symbol}</a><span className="company">{r.pattern}</span></TableCell><TableCell>{r.direction}</TableCell><TableCell><strong style={{color:strengthColor(r.strength?.label??'Unrated')}}>{r.strength?.label??'Unrated'}</strong></TableCell><TableCell>{r.strength?`${r.strength.score}/100`:'—'}</TableCell><TableCell>{r.relativeVolume.toFixed(2)}×</TableCell><TableCell>{r.strength?`${r.strength.breakInRanges.toFixed(2)}× avg. true range`:'—'}</TableCell></TableRow>)}</TableBody></Table>}
 <details style={{marginTop:16}}><summary>How strength is graded</summary><p>Strong requires volume ≥1.5× average, a close ≥0.30× the previous 14-session average true range beyond the boundary, a close in the outer 35% of the candle toward the breakout, and an evidence score ≥70.</p><p>Weak means volume &lt;1.10×, a break &lt;0.10× average true range, or a close in the opposite half of the candle. Everything else is Moderate. A high score alone cannot override a weak component.</p><p>Score weights: volume up to 40 points, break distance up to 40, and close position up to 20. These are initial heuristic thresholds, not calibrated forecasts. All baselines exclude the signal candle.</p></details></section>
 <label style={{display:'block',margin:'16px 0'}}><input type="checkbox" checked={showRejected} onChange={e=>setShowRejected(e.target.checked)}/> Show rejected findings and reasons</label>
 {visible.length===0&&report.reviewed>0&&<p>No patterns match this strength filter.</p>}
 {visible.map((r,i)=><article id={"pattern-"+r.symbol+"-"+r.pattern.replaceAll(" ","-")} key={r.symbol+r.pattern+i} style={{borderTop:'1px solid #34414e',padding:'16px 0'}}><h3>{r.symbol} · {r.pattern} · {r.status==='Confirmed'?'Rules confirmed':r.status}</h3>{r.strength&&<div style={{borderLeft:'4px solid '+strengthColor(r.strength.label),padding:'8px 16px',margin:'12px 0'}}><strong style={{color:strengthColor(r.strength.label)}}>{r.strength.label} {r.direction.toLowerCase()} · {r.strength.score}/100 evidence score</strong><ul>{r.strength.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}<p>{r.reason}</p><p className="muted">{r.date} · Close ${r.close.toFixed(2)}{r.level!==null?' · Boundary $'+r.level.toFixed(2):''} · Volume {r.relativeVolume.toFixed(3)}×</p><p>{r.proposal.explanation}</p>{r.averageDollarVolume!==undefined&&<p><strong>Liquidity rank #{r.liquidityRank}</strong> · 20-day average dollar volume ${(r.averageDollarVolume/1e6).toFixed(1)}M/day · Market cap ${(r.cap/1e9).toFixed(1)}B</p>}{r.status==='Confirmed'&&(r.chart||report.charts[r.symbol])&&<img src={r.chart||report.charts[r.symbol]} alt={r.symbol+' daily candles and volume; validated boundary in yellow'} style={{width:'100%',height:'auto'}}/>}</article>)}
 {report.errors.length>0&&<details><summary>Coverage and setup notes ({report.errors.length})</summary><ul>{report.errors.map(e=><li key={e.symbol}>{e.symbol}: {e.reason}</li>)}</ul></details>}
 {Object.entries(report.charts).filter(([symbol])=>['SNDK','INTC'].includes(symbol)&&!confirmed.some(r=>r.symbol===symbol)).map(([symbol,url])=><article key={symbol} style={{borderTop:'1px solid #34414e',padding:'20px 0'}}><h3>{symbol} · Daily price and volume</h3><p className="muted">Saved chart · No confirmed price-rule pattern in this scan.</p><img src={url} alt={symbol+' daily candle and volume chart'} width={1240} height={720} style={{display:'block',width:'100%',height:'auto'}}/><a href={url} target="_blank" rel="noreferrer">Open {symbol} chart full size ↗</a></article>)}
 <p className="muted" style={{marginTop:16}}>{report.source}{report.generatedAt?' · Generated '+new Date(report.generatedAt).toLocaleString():''}</p><a href="/pattern-results.json" download>Download pattern report</a>
 </>}</div></section>;
}
