import assert from 'node:assert/strict';
import {scoreStrength,rankStrength} from './strength.ts';
import type {Stock} from './scanner';
import type {PatternResult} from './patterns';
const stock=():Stock=>({symbol:'TEST',name:'Synthetic',cap:6e9,bars:Array.from({length:61},(_,i)=>({date:new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10),open:100,close:i===60?104:100,high:i===60?105:101,low:99,volume:i===60?200:100,final:true}))});
const result=(s:Stock):PatternResult=>({symbol:s.symbol,pattern:'Bull flag',status:'Confirmed',reason:'fixture',proposal:{pattern:'Bull flag',start:'',end:'',upper:[],lower:[],turns:[],poleStart:null,poleEnd:null,explanation:''},date:s.bars.at(-1)!.date,direction:'Breakout',level:101,close:104,relativeVolume:2,cap:6e9,line:[]});
let s=stock(),r=result(s);assert.equal(scoreStrength(s,r)!.label,'Strong');assert.equal(scoreStrength(s,r)!.averageTrueRange,2);
s.bars.at(-1)!.volume=105;assert.equal(scoreStrength(s,r)!.label,'Weak');
s=stock();s.bars.at(-1)!.volume=125;assert.equal(scoreStrength(s,result(s))!.label,'Moderate');
s=stock();r=result(s);r.level=103.9;assert.equal(scoreStrength(s,r)!.label,'Weak');
s=stock();s.bars.at(-1)!.high=120;assert.equal(scoreStrength(s,result(s))!.label,'Weak');assert.equal(scoreStrength(s,result(s))!.averageTrueRange,2);
s=stock();r=result(s);s.bars.forEach(b=>{const {open,close,high,low}=b;Object.assign(b,{open:200-open,close:200-close,high:200-low,low:200-high});});Object.assign(r,{direction:'Breakdown',level:99,close:96});assert.equal(scoreStrength(s,r)!.label,'Strong');
s=stock();r=result(s);r.status='Rejected';assert.equal(scoreStrength(s,r),null);
s=stock();s.bars.at(-1)!.final=false;assert.equal(scoreStrength(s,result(s)),null);
s=stock();r=result(s);r.date='wrong';assert.equal(scoreStrength(s,r),null);
s=stock();s.bars.at(-1)!.volume=100;assert.equal(scoreStrength(s,result(s)),null);
s=stock();r=result(s);r.level=104;assert.equal(scoreStrength(s,r),null);
s=stock();r=result(s);s.bars[0].close=NaN;assert.equal(scoreStrength(s,r),null);
s=stock();r=result(s);const strong={...r,strength:scoreStrength(s,r)};s.bars.at(-1)!.volume=105;const weak={...r,strength:scoreStrength(s,r)};assert.deepEqual([weak,strong].sort(rankStrength).map(x=>x.strength?.label),['Strong','Weak']);
console.log('Strength tests passed: strong/moderate/weak, bearish symmetry, no baseline lookahead, invalid data, strict confirmation and sorting.');
